import { FilterConfig, LootGroup } from "../types/FilterTypes";
import {
  BLACK,
  CARAMEL,
  GOLD,
  GREEN,
  KHAKI,
  NO_COLOR,
  RED,
  WHITE
} from "../types/hexcolor";

// Item lists by tier
const S_TIER_UNIQUES = [
  "*champion scroll",
  "Infernal Cape",
  "Fire Cape",
  "Dizana's Quiver*",
  "*Max Cape",
  "Unsired",
  "Ancient blood ornament kit",
  "Ultor vestige",
  "Executioner's axe head",
  "Venator vestige",
  "Leviathan's lure",
  "Bellator vestige",
  "Siren's staff",
  "Magus vestige",
  "Eye of the duke",
  "*mutagen",
  "Slepey Tablet",
];

const A_TIER_UNIQUES = [
  "Brimstone key",
  "Jar of*",
  "Noxious pommel",
  "Noxious point",
  "*half of key (moon key)",
  "Hill giant club"
];


const B_TIER_UNIQUES = [
  "Dark totem",
  "Mossy key",
  "Giant key",
  "Ecumenical key",
  "Abyssal head",
  "Araxyte head",
  "Alchemical hydra heads",
  "Kbd heads",
  "Kq head*",
  "Dark claw",
  "Bludgeon claw",
  "Bludgeon spine",
  "Bludgeon axon",
  "Hydra's eye",
  "Hydra's fang",
  "Hydra's heart",
  "Strangled tablet",
  "Scarred tablet",
  "Sirenic tablet",
  "Frozen tablet",
  "Scurrius' spine",
  "Vorkath's head",
];

const C_TIER_UNIQUES = [
  "Dark totem top",
  "Dark totem base",
  "Dark totem middle",
  "Long bone",
  "Curved bone",
  "Looting bag",
  "Unidentified small fossil",
  "Unidentified medium fossil",
  "Unidentified large fossil",
  "Unidentified rare fossil",
  "Key master teleport",
  "Chromium ingot",
  "Blood quartz",
  "Smoke quartz",
  "Shadow quartz",
  "Ice quartz",
  "Pendant of ates*",
  "Frozen cache",
  "Ancient icon",
  "Charged Ice",
  "Parasitic egg",
];

const D_TIER_VALUES = [
  "Dragon bones",
  "Dagannoth bones",
  "Frozen tear",
  "Zulrah's scales",
  "Sunfire splinters",
  "Ancient essence",
  "Granite dust",
  "Crystal shard",
];

const E_TIER_VALUES = [
  "Archery ticket",
  "Mole claw",
  "Mole skin",
  "Trading sticks",
  "Shantay pass",
  "Ship ticket",
  "Abyssal pearls",
  "Anima-infused bark",
  "Agility arena ticket",
  "Barronite shards",
  "Blood money",
  "Brimhaven voucher",
  "Castle wars ticket",
  "Ecto-token",
  "Frog token",
  "Golden nugget",
  "Glistening tear",
  "Hallowed mark",
  "Intelligence",
  "Mark of grace",
  "Mermaid's tear",
  "Minnow",
  "Molch pearl",
  "Nuggets",
  "Paramaya ticket",
  "Rare creature parts",
  "Reward token credits",
  "Stardust",
  "Tokkul",
  "Termites",
  "Unidentified minerals",
  "Warrior guild token",
  "Blessed bone shards",
  "Sun-kissed bones",
  "Ecumenical key shard",
];

const DEFAULT_LOOT_GROUPS: LootGroup[] = [
  {
    name: "S_TIER",
    foregroundColor: RED,
    borderColor: RED,
    backgroundColor: NO_COLOR,
    beam: true,
    valueThreshold: 100_000_000,
    items: [...S_TIER_UNIQUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "A_TIER",
    foregroundColor: WHITE,
    borderColor: WHITE,
    backgroundColor: NO_COLOR,
    beam: true,
    valueThreshold: 10_000_000,
    items: [...A_TIER_UNIQUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "B_TIER",
    foregroundColor: BLACK,
    borderColor: BLACK,
    backgroundColor: NO_COLOR,
    beam: false,
    valueThreshold: 1_000_000,
    items: [...B_TIER_UNIQUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "C_TIER",
    foregroundColor: CARAMEL,
    borderColor: CARAMEL,
    backgroundColor: NO_COLOR,
    beam: false,
    valueThreshold: 500_000,
    items: [...C_TIER_UNIQUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "D_TIER",
    foregroundColor: GOLD,
    borderColor: GOLD,
    backgroundColor: NO_COLOR,
    beam: false,
    valueThreshold: 100_000,
    items: [...D_TIER_VALUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "E_TIER",
    foregroundColor: KHAKI,
    borderColor: KHAKI,
    backgroundColor: NO_COLOR,
    beam: false,
    valueThreshold: 20_000,
    items: [...E_TIER_VALUES.map((item) => ({ name: item, matcher: item }))],
  },
  {
    name: "HERB_GROUP",
    foregroundColor: GREEN,
    borderColor: GREEN,
    backgroundColor: NO_COLOR,
    beam: false,
    valueThreshold: 0,
  },
];


export const DEFAULT_CONFIG: FilterConfig = {
  lootGroups: DEFAULT_LOOT_GROUPS,
  date: new Date(),
  includePreamble: false,
};
